name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Base Image
      uses: docker/build-push-action@v3
      with:
        context: base-image/.
        push: true
        tags: pervage/infra-base:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/infra-base:latest
  maven:
    runs-on: ubuntu-latest
    needs: base
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Math Calculator
      uses: docker/build-push-action@v3
      with:
        context: math-calculator/.
        push: true
        tags: pervage/calculation:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/calculation:latest
  npm:
    runs-on: ubuntu-latest
    needs: base
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Node Module
      uses: docker/build-push-action@v3
      with:
        context: npm/.
        push: true
        tags: pervage/npm-build:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/npm-build:latest
  multi-stage:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Multi Stage
      uses: docker/build-push-action@v3
      with:
        context: multi-stage/.
        push: true
        tags: pervage/multistage:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/multistage:latest
  busybox:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build Busybox Stage
      uses: docker/build-push-action@v3
      with:
        context: busybox/.
        push: false
        tags: pervage/busybox:latest
    -
      name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output-dns.txt
        retention-days: 90
  
