name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Base Image
      run: |
        echo "${{ secrets.DOCKER_PWD }}" | docker login -u "pervage" --password-stdin
        ls -l
        docker build . --file infra-base/Dockerfile --tag pervage/infra-base:latest
        docker push pervage/infra-base

    - uses: actions/checkout@v3
    - name: Build the Calculation Image
      run: |
        echo "${{ secrets.DOCKER_PWD }}" | docker login -u "pervage" --password-stdin
        docker build . --file math-calculator/Dockerfile --tag pervage/calculations:latest
        docker push pervage/calculations