name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: base-image/Dockerfile
        push: true
        tags: pervage/infra-base:latest
    