name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Base Image
      uses: docker/build-push-action@v3
      with:
        context: /base-image/.
        push: true
        tags: pervage/infra-base:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/infra-base:latest
  maven:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Math Calculator
      uses: docker/build-push-action@v3
      with:
        context: /math-calculator/.
        push: false
        tags: pervage/calculation:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/calculation:latest
  npm:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Node Module
      uses: docker/build-push-action@v3
      with:
        context: /npm/.
        push: false
        tags: pervage/node:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/node:latest
  multi-stage:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
      name: Git Checkout
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    -
      name: Build Multi Stage
      uses: docker/build-push-action@v3
      with:
        context: /multi-stage/.
        push: false
        tags: pervage/multistage:latest
    -
      name: Scan for vulnerabilities
      uses: crazy-max/ghaction-container-scan@v2
      with:
        image: pervage/multistage:latest